name: Deploy to EC2

on:
  push:
    branches:
      - main   # deploy when pushing to main branch

jobs:
  deploy:
    name: Deploy Node.js Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying Node.js server on EC2..."
            cd /home/ec2-user/crud_services/crud-service
            # Reset local changes & pull latest code
            git checkout -- .
            git pull

            # Install dependencies
            npm install

            # Restart app with PM2 (ensure pm2 is installed globally)
            pm2 stop all || true
            pm2 start server.js --name "crud_services"
            pm2 save
